# Generated by Django 3.2.18 on 2023-05-01 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=256)),
                ('sub', models.CharField(max_length=256)),
                ('cstream', models.CharField(max_length=256)),
                ('cyear', models.CharField(max_length=256)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('cstream', models.CharField(max_length=256)),
                ('cyear', models.CharField(max_length=256)),
                ('notes', models.FileField(upload_to='pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=512)),
                ('opt1', models.CharField(max_length=256)),
                ('opt2', models.CharField(max_length=256)),
                ('opt3', models.CharField(max_length=256)),
                ('opt4', models.CharField(max_length=256)),
                ('ans', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('gender', models.CharField(max_length=512)),
                ('class_stream', models.CharField(max_length=512)),
                ('class_year', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=256)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAApp.question')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assres', models.FileField(upload_to='assignment_responses')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAApp.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAApp.student')),
            ],
        ),
    ]
